### ISSUE TITLE
Fetch more information from ClassyFire requests

### ISSUE THREAD

**Issue by Treutler** [aberHRML/classyfireR#23]
We perform ClassyFire requests on a regular basis and already have proprietary code for this. However, we would prefer to use a common solution for this and this repo seems great for this purpose.

We fetch and use more information from ClassyFire compared to your solution, namely
- The structure encoded by InChI, SMILES, and InChIKey
- Identified and predicted ChEBI IDs
- CHEMONT name and CHEMONT ID of the main class (e.g. 'Organic compounds; Lignans, neolignans' and related compounds and 'CHEMONTID:0000000; CHEMONTID:0001392')
- CHEMONT names and CHEMONT IDs of the alternative parents
- Substituent names

Is it an option for you to have all these properties in the result of your package?

**Comment by wilsontom** [comment]
Hi,
The new version of `classyfireR v0.3.0` is on CRAN now and returns all this extra information. 
Any problems, please get in touch

Tom
