### ISSUE TITLE
failing for lot of InChIKeys

### ISSUE THREAD

**Issue by jliigand** [aberHRML/classyfireR#35]
Hi there,

I tried to run today the function and it failed for a lot of compounds (75 out of 135 in my compound set, mainly metabolites) (I checked these compounds have computed classifications on the original page).
I used such function to run it
`result <- get_classification(str_replace(inchikey,
                                           pattern = "InChIKey=",
                                           replacement = ""))`
The error message I get is:
```
ERROR : All columns in a tibble must be 1d or 2d objects:
* Column `source` is NULL
* Column `source_id` is NULL
* Column `annotations` is NULL
```
What can cause such error?
Best regards,
Jaanus

The failing examples are:
KKMZQOIASVGJQE-UHFFFAOYSA-N, ZFCHNZDUMIOWFV-UHFFFAOYSA-N, YEGKYFQLKYGHAR-UHFFFAOYSA-N, BNQYXFAVUMPZFG-UHFFFAOYSA-N, RPHLQSHHTJORHI-UHFFFAOYSA-N, UQTZMGFTRHFAAM-UHFFFAOYSA-N, CGMJQQJSWIRRRL-UHFFFAOYSA-N, JIWBIWFOSCKQMA-UHFFFAOYSA-N, ZJAZCYLYLVCSNH-UHFFFAOYSA-N, SQVRNKJHWKZAKO-UHFFFAOYSA-N, VHSVKVWHYFBIFJ-UHFFFAOYSA-N, ZNJFBWYDHIGLCU-UHFFFAOYSA-N, FJLUATLTXUNBOT-UHFFFAOYSA-N, RZRPTBIGEANTGU-UHFFFAOYSA-N, HBFCVDJQUPEEIC-UHFFFAOYSA-N, NOKPBJYHPHHWAN-UHFFFAOYSA-N, URFCJEUYXNAHFI-UHFFFAOYSA-N, SQKRUBZPTNJQEM-UHFFFAOYSA-N, SJNRNWWBXZOALQ-UHFFFAOYSA-N, PKFBJSDMCRJYDC-UHFFFAOYSA-N, FTMZLSDESAOPSZ-UHFFFAOYSA-N, WJLUHPKQYRNGFP-UHFFFAOYSA-N, GXZQHMHLHHUHAM-UHFFFAOYSA-N, HPFXACZRFJDURI-UHFFFAOYSA-N, DCJBINATHQHPKO-UHFFFAOYSA-N, PJHOFUXBXJNUAC-UHFFFAOYSA-N, PEGCITODQASXKH-UHFFFAOYSA-N, WECGLUPZRHILCT-UHFFFAOYSA-N, SKLUWKYNZNXSLX-UHFFFAOYSA-N, GWNVDXQDILPJIG-UHFFFAOYSA-N, VRQVVMDWGGWHTJ-UHFFFAOYSA-N, DBMKKVSGBYKSFI-UHFFFAOYSA-N, XFUXZHQUWPFWPR-UHFFFAOYSA-N, QSZKEDWVAOAFQY-UHFFFAOYSA-N, VCWLZDVWHQVAJU-UHFFFAOYSA-N, FIXJQRIEAIDXEN-UHFFFAOYSA-N, YAWJNUREPGJHSG-UHFFFAOYSA-N, RUDVTXZKYPJLFH-UHFFFAOYSA-N, ULSDMUVEXKOYBU-UHFFFAOYSA-N, DJKDIKIDYDXHDD-UHFFFAOYSA-N, JKUDIEXTAYKJNX-UHFFFAOYSA-N, OTZRAYGBFWZKMX-UHFFFAOYSA-N, RXECVCDYORIBBT-UHFFFAOYSA-N, UPSONEVYPXSPEI-UHFFFAOYSA-N, DEFJQIDDEAULHB-UHFFFAOYSA-N, CZCIKBSVHDNIDH-UHFFFAOYSA-N, XDXDZDZNSLXDNA-UHFFFAOYSA-N, XKGDWZQXVZSXAO-UHFFFAOYSA-N, ZUDXFBWDXVNRKF-UHFFFAOYSA-N, QJIXVOQAEZMUIH-UHFFFAOYSA-N, YEESKJGWJFYOOK-UHFFFAOYSA-N, ICDMLAQPOAVWNH-UHFFFAOYSA-N, XOZLRRYPUKAKMU-UHFFFAOYSA-N, XAWCMDFDFNRKGK-UHFFFAOYSA-N, MEHJVKGETWKOKY-UHFFFAOYSA-N, GRUSXPIAJWRLRQ-UHFFFAOYSA-N, SEPPVOUBHWNCAW-UHFFFAOYSA-N, WILLZMOKUUPJSL-UHFFFAOYSA-N, BSQFBMXCQIKYNI-UHFFFAOYSA-N, YKGQBEGMUSSPFY-UHFFFAOYSA-N, NTNWOCRCBQPEKQ-UHFFFAOYSA-N, IBFIBMHGNMSQLB-UHFFFAOYSA-N, OYHQOLUKZRVURQ-UHFFFAOYSA-N, BXJAMTIXSSLKAH-UHFFFAOYSA-N, YRUGYYZQISUWGN-UHFFFAOYSA-N, FMVHVRYFQIXOAF-UHFFFAOYSA-N, IDGQXGPQOGUGIX-UHFFFAOYSA-N, FMMOOAYVCKXGMF-UHFFFAOYSA-N, CQIUKKVOEOPUDV-UHFFFAOYSA-N, ZIDQIOZJEJFMOH-UHFFFAOYSA-N, KTHDTJVBEPMMGL-UHFFFAOYSA-N, HSRAJJQTYQHRSA-UHFFFAOYSA-N, UVCOILFBWYKHHB-UHFFFAOYSA-N, MEASLHGILYBXFO-UHFFFAOYSA-N

**Comment by wilsontom** [comment]
Hi Jaanus,

Can you run the following in your R session `packageVersion('classyfireR')` the output should be 0.3.2.
 You probably just need to install the development version of the package from GitHub. You can do this using the following

```
remotes::install_github('aberHRML/classyfireR')
```

Thanks

Tom

**Comment by jliigand** [comment]
Hi Tom, 

Thank you for your swift reply. Indeed, I had an older version (0.3.0) and it looks it solved the problem. 
Thank you for your help.

Best regards,
Jaanus
