### ISSUE TITLE
Error in get_classification(df[i, ]) : Request rate limit exceeded!

### ISSUE THREAD

**Issue by Adafede** [aberHRML/classyfireR#36]
Hi,

I think title says it all...do you think there is a quick fix to override this limit of I'll simply have to split my dfs?

Thanks a lot for your work

**Comment by wilsontom** [comment]
The easiest "quick-fix" would be to include a `Sys,sleep(0.2)` while you are iterating over your data frame

Thanks

Tom

**Comment by Adafede** [comment]
Thank you very much for your answer. It works indeed, as I have a lot to classify, do you know the exact limit of the API? 
Thanks a lot again

**Comment by jasenfinch** [comment]
I think it is currently 12 requests per minute

**Comment by Adafede** [comment]
Sadly what I observed...will be looooooong x(
