### ISSUE TITLE
Better submit_query() diagnostics and error handling

### ISSUE THREAD

**Issue by sneumann** [aberHRML/classyfireR#45]
Hi,
when submitting a weird list of e.g. 2000 SMILES, we (@Flow191 and me) the result returned was a list of just six entries. I would expect a result list of the same length 2000 (possibly with null values where no result was returned). Otherwise, the docs should give instructions (and the code check ?!) that the input has named structures, so that the results can be linked to entries in the query. We learned that the hard way ;-) 
Yours, 
Steffen

**Comment by wilsontom** [comment]
All sorted in latest CRAN release

Tom
