### ISSUE TITLE
Local caching [enhancement]

### ISSUE THREAD

**Issue by sneumann** [aberHRML/classyfireR#46]
Hi, 
running a large number of queries takes a while, and puts quite some burden onto the REST servers. It would be great to have a local caching. This could be integrated into the query, lookup in the cache, and return the JSON response. If not found, it would query remotely, add the results to the cache, and continue as normal. The local cache could be an SQLite database for quick lookup and insert, or (much simpler but less robust) just an `*.rdata` object in the home directory or a specified location. 
Yours, Steffen

**Comment by wilsontom** [comment]
All sorted in the latest CRAN release thanks to @Flow191
